// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanSach.Data;

#nullable disable

namespace WebBanSach.Migrations
{
    [DbContext(typeof(dbcontext))]
    [Migration("20220620025347_ht")]
    partial class ht
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebBanSach.Models.HoaDon", b =>
                {
                    b.Property<string>("ID_HoaDon")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayMua")
                        .HasColumnType("datetime2");

                    b.Property<double>("TongTien")
                        .HasColumnType("float");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_HoaDon");

                    b.HasIndex("MaKH");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("WebBanSach.Models.HoaDonCT", b =>
                {
                    b.Property<string>("ID_HDCT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ID_HDCT");

                    b.HasIndex("MaHoaDon");

                    b.HasIndex("MaSach");

                    b.ToTable("HoaDonCT");
                });

            modelBuilder.Entity("WebBanSach.Models.KhachHang", b =>
                {
                    b.Property<string>("ID_KhachHang")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_KhachHang");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("WebBanSach.Models.Kho", b =>
                {
                    b.Property<string>("ID_Kho")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("GiaNhap")
                        .HasColumnType("float");

                    b.Property<string>("MaNhanVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_Kho");

                    b.HasIndex("MaNhanVien");

                    b.HasIndex("MaSach");

                    b.ToTable("Khos");
                });

            modelBuilder.Entity("WebBanSach.Models.NhanVien", b =>
                {
                    b.Property<string>("ID_NhanVien")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Quyen")
                        .HasColumnType("bit");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_NhanVien");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("WebBanSach.Models.NhaXuatBan", b =>
                {
                    b.Property<string>("ID_NXB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenXuatBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_NXB");

                    b.HasIndex("TenXuatBan")
                        .IsUnique();

                    b.ToTable("NhaXuatBan");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.Property<string>("ID_Sach")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNXB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int>("SoTrang")
                        .HasColumnType("int");

                    b.Property<int>("TaiBan")
                        .HasColumnType("int");

                    b.Property<string>("TenSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_Sach");

                    b.HasIndex("MaNXB");

                    b.HasIndex("TenSach", "TaiBan", "MaNXB")
                        .IsUnique();

                    b.ToTable("Sach");
                });

            modelBuilder.Entity("WebBanSach.Models.SachCT", b =>
                {
                    b.Property<string>("ID_SachCT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSach")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTacGia")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaTheLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_SachCT");

                    b.HasIndex("MaSach");

                    b.HasIndex("MaTacGia");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("SachCT");
                });

            modelBuilder.Entity("WebBanSach.Models.TacGia", b =>
                {
                    b.Property<string>("ID_TacGia")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoVaTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("QueQuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("ID_TacGia");

                    b.ToTable("TacGia");
                });

            modelBuilder.Entity("WebBanSach.Models.TheLoai", b =>
                {
                    b.Property<string>("ID_TheLoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenTL")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID_TheLoai");

                    b.HasIndex("TenTL")
                        .IsUnique();

                    b.ToTable("TheLoai");
                });

            modelBuilder.Entity("WebBanSach.Models.HoaDon", b =>
                {
                    b.HasOne("WebBanSach.Models.KhachHang", "KhachHang")
                        .WithMany("HoaDons")
                        .HasForeignKey("MaKH")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("WebBanSach.Models.HoaDonCT", b =>
                {
                    b.HasOne("WebBanSach.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("MaHoaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.Sach", "Sach")
                        .WithMany("HoaDonCTs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HoaDon");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebBanSach.Models.Kho", b =>
                {
                    b.HasOne("WebBanSach.Models.NhanVien", "NhanVien")
                        .WithMany("Khos")
                        .HasForeignKey("MaNhanVien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.Sach", "Sach")
                        .WithMany("Khos")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("Sach");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.HasOne("WebBanSach.Models.NhaXuatBan", "NhaXuatBan")
                        .WithMany("Sachs")
                        .HasForeignKey("MaNXB")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NhaXuatBan");
                });

            modelBuilder.Entity("WebBanSach.Models.SachCT", b =>
                {
                    b.HasOne("WebBanSach.Models.Sach", "Sach")
                        .WithMany("SachCTs")
                        .HasForeignKey("MaSach")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.TacGia", "TacGia")
                        .WithMany("SachCTs")
                        .HasForeignKey("MaTacGia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebBanSach.Models.TheLoai", "TheLoai")
                        .WithMany("SachCTs")
                        .HasForeignKey("MaTheLoai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sach");

                    b.Navigation("TacGia");

                    b.Navigation("TheLoai");
                });

            modelBuilder.Entity("WebBanSach.Models.KhachHang", b =>
                {
                    b.Navigation("HoaDons");
                });

            modelBuilder.Entity("WebBanSach.Models.NhanVien", b =>
                {
                    b.Navigation("Khos");
                });

            modelBuilder.Entity("WebBanSach.Models.NhaXuatBan", b =>
                {
                    b.Navigation("Sachs");
                });

            modelBuilder.Entity("WebBanSach.Models.Sach", b =>
                {
                    b.Navigation("HoaDonCTs");

                    b.Navigation("Khos");

                    b.Navigation("SachCTs");
                });

            modelBuilder.Entity("WebBanSach.Models.TacGia", b =>
                {
                    b.Navigation("SachCTs");
                });

            modelBuilder.Entity("WebBanSach.Models.TheLoai", b =>
                {
                    b.Navigation("SachCTs");
                });
#pragma warning restore 612, 618
        }
    }
}
